### ISSUE TITLE
Consider adding a `client_name` value for dynamic registration

### ISSUE THREAD

**Issue by markcraig** [ForgeRock/openid#8]
When dynamically registering with an OpenID Provider, the `client_id` is very likely a randomly generated string.

The optional `client_name` can be provided as a human-readable alternative when requesting end-user consent.

A realistic example of dynamic registration should therefore include a `client_name` value.

**Comment by markcraig** [comment]
@forgerock-chris , does this one make sense to you?

**Comment by forgerock-chris** [comment]
Yep, in fact I've just updated the OpenAM docs to say much the same, otherwise the auto-generated `client_id` is used in the consent pages.

**Comment by markcraig** [comment]
I've done a PR for this one and mentioned you in the comment so you get notified.

**Comment by markcraig** [comment]
PR has been merged
